language: csharp
solution: EndlessAdventure.sln
matrix:
  include:
    - os: osx
      osx_image: xcode9
      dotnet: 1.1.4
      mono: none
      env: DOTNETCORE=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.1
      mono: none
      env: DOTNETCORE=1
install:
  - nuget restore EndlessAdventure.sln
  - nuget install NUnit.ConsoleRunner -Version 3.7.0 -OutputDirectory testrunner
script:
  - dotnet restore
  - dotnet build -c Release
#  - msbuild EndlessAdventure.sln /p:TargetFrameworkVersion="v4.6.1" /p:Configuration=Release
#  - ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./EndlessAdventure.Tests/bin/Release/netstandard1.4/EndlessAdventure.Tests.dll